/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2022-03-31 04:55:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import epp.sayhi.toy.model.Product;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/Users/yujin/toyProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SayHi/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/yujin/toyProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SayHi/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1329370132000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1638470368687L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar", Long.valueOf(1638470367069L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("epp.sayhi.toy.model.Product");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>상품 상세 페이지</title>\n");
      out.write("<style>\n");
      out.write(".container {\n");
      out.write("	max-width: 1300px;\n");
      out.write("	margin: auto;\n");
      out.write("	padding-left: 25px;\n");
      out.write("	padding-right: 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".row {\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	flex-wrap: wrap;\n");
      out.write("	justify-content: space-around;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".col-2 {\n");
      out.write("	flex-basis: 50%;\n");
      out.write("	mid-width: 300px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".col-2 img {\n");
      out.write("	max-width: 100%;\n");
      out.write("	padding: 50px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".single-product {\n");
      out.write("	margin-top: 80px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".single-product .col-2 img {\n");
      out.write("	padding: 0;\n");
      out.write("	padding-right: 10px;\n");
      out.write("	margin: 20px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".single-product .col-2 {\n");
      out.write("	padding: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".single-product h4 {\n");
      out.write("	margin: 20px 0;\n");
      out.write("	font-size: 22px;\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".single-product select {\n");
      out.write("	display: block;\n");
      out.write("	padding: 10px;\n");
      out.write("	margin-top: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".single-product input {\n");
      out.write("	width: 50px;\n");
      out.write("	height: 40px;\n");
      out.write("	padding-left: 10px;\n");
      out.write("	font-size: 20px;\n");
      out.write("	margin-right: 10px;\n");
      out.write("	border: 1px solid #ff523b;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input:focus {\n");
      out.write("	outline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@charset \"UTF-8\";\n");
      out.write("@import url(https://fonts.google.com/earlyaccess/nanumgothic.css);\n");
      out.write("\n");
      out.write(".search-container{\n");
      out.write("    float: left;\n");
      out.write("    margin-right: 500px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-box {\n");
      out.write("    display: inline-block;\n");
      out.write("    margin-top: 15px;\n");
      out.write("    width: 230px;\n");
      out.write("    height: 30px;\n");
      out.write("    border: none;\n");
      out.write("    font-size: 16px;\n");
      out.write("    padding-left: 20px;\n");
      out.write("    font-family: nanumgothic;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-box::placeholder{\n");
      out.write("    color: rgb(169, 169, 169);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-box:focus {\n");
      out.write("    outline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search {\n");
      out.write("    float: right;\n");
      out.write("    height: 32px;\n");
      out.write("    width: 32px;\n");
      out.write("    margin-top: 15px;\n");
      out.write("    background: black;\n");
      out.write("    color: white;\n");
      out.write("    font-size: 17px;\n");
      out.write("    border: solid 1px grey;\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("  \n");
      out.write(".main-page {\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: row;\n");
      out.write("    justify-content: center;\n");
      out.write("    align-content: center;\n");
      out.write("    align-items: center;\n");
      out.write("    flex-wrap: wrap;\n");
      out.write("    width: 100vw;\n");
      out.write("    height: 100vh;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* .main-background {\n");
      out.write("    width: 100%;\n");
      out.write("    height: 100%;\n");
      out.write("    background-size: 1500px 500px;\n");
      out.write("    background-image: url(\"../../resources/img/main_background2.jpg\");\n");
      out.write("    background-repeat: repeat-x;\n");
      out.write("    animation: scroll 40s linear infinite;\n");
      out.write("}\n");
      out.write("  \n");
      out.write("@keyframes scroll {\n");
      out.write("    from {\n");
      out.write("        background-position: left calc(4.84 * min(100vh, 750px)) top 0px;\n");
      out.write("    }\n");
      out.write("    to {\n");
      out.write("        background-position: left 0px top 0px;\n");
      out.write("    }\n");
      out.write("} */\n");
      out.write("\n");
      out.write(".main-bar {\n");
      out.write("    position: absolute;\n");
      out.write("    overflow: hidden;\n");
      out.write("    display: inline;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content {\n");
      out.write("    margin-top: -100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".navbar {\n");
      out.write("    box-shadow: 0 2px 0 0 rgba(0,0,0,.2);\n");
      out.write("    background-color: black;\n");
      out.write("    font-family: nanumgothic;\n");
      out.write("    overflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-btn {\n");
      out.write("    margin-top: 20px;\n");
      out.write("    margin-right: 10px;\n");
      out.write("    border-width: 1px;\n");
      out.write("    border-style: solid;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    border-color: rgb(221, 221, 221);\n");
      out.write("    padding: 5px; \n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-btn:hover {\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-bar {\n");
      out.write("    float: left;\n");
      out.write("    overflow: hidden;\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown {\n");
      out.write("	font-size: 20px;\n");
      out.write("	display: none;\n");
      out.write("    position: absolute;\n");
      out.write("    background-color: white;\n");
      out.write("    min-width: 160px;\n");
      out.write("    border: solid 1px lightgrey;\n");
      out.write("    top: 140px;\n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown a {\n");
      out.write("    color: black;\n");
      out.write("    padding: 12px 16px;\n");
      out.write("    border: solid 1px lightgrey;\n");
      out.write("    text-decoration: none;\n");
      out.write("    font-weight: bold;\n");
      out.write("    display: block;\n");
      out.write("    text-align: center;\n");
      out.write("    position: relative;\n");
      out.write("    z-index: 3;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown a:hover{\n");
      out.write("    background-color: lightgrey;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-bar:hover .dropdown{\n");
      out.write("    display: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".desc {\n");
      out.write("    font-size: 12px;\n");
      out.write("    font-weight: normal;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main {\n");
      out.write("    list-style-type: none;\n");
      out.write("    text-align: center;\n");
      out.write("    padding-left: 20px;\n");
      out.write("    padding-right: 9px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bar {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    align-items: center;\n");
      out.write("    text-align: center;\n");
      out.write("    padding-left: 60px;\n");
      out.write("    padding-right: 29px;\n");
      out.write("    padding-bottom: 10px;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bar a:hover {\n");
      out.write("    background-color: rgba(0,0,0,.1);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-right-contact {\n");
      out.write("    padding-left: 25px;\n");
      out.write("    float: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-list{\n");
      out.write("	margin-left: 200px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".left-menu {\n");
      out.write("    float: left;\n");
      out.write("    position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".ad {\n");
      out.write("    background-color: rgb(242, 242, 242);\n");
      out.write("    height: 250px;\n");
      out.write("    text-align: center;\n");
      out.write("    margin-top: 80px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".ad-content { \n");
      out.write("    padding-top: 100px;\n");
      out.write("    font-size: 50px;\n");
      out.write("    font-weight: bold;\n");
      out.write("    color: rgb(73, 73, 73);\n");
      out.write("}\n");
      out.write(".contact {\n");
      out.write("    color:rgb(25, 31, 140) !important;\n");
      out.write("    text-align: right;\n");
      out.write("    padding-right: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact-icon {\n");
      out.write("    position: absolute;\n");
      out.write("    float: right;\n");
      out.write("    top: 5%;\n");
      out.write("    margin-left: -3px;\n");
      out.write("    left: 97%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("#banner {\n");
      out.write("	width: 100%;\n");
      out.write("	height: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#logo {\n");
      out.write("    width: 168px;\n");
      out.write("    height: 45px;\n");
      out.write("    margin: 7px 20px 0px 12px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    display: flex;\n");
      out.write("    float: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav {\n");
      out.write("    list-style-type: none;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 7px 0px 7px 0px;\n");
      out.write("    overflow: hidden;\n");
      out.write("    background-color: black;\n");
      out.write("    color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#main-text {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    color:rgba(0,0,0,.9);\n");
      out.write("    font-size: 38px;\n");
      out.write("    font-weight: bold;\n");
      out.write("    margin-top: 100px;\n");
      out.write("    font-family: nanumgothic;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu{\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("    float: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a {\n");
      out.write("    display: block;\n");
      out.write("    margin-right: 38px;\n");
      out.write("    margin-top: 18px;\n");
      out.write("    text-align: left;\n");
      out.write("    text-decoration: none;\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a:hover {\n");
      out.write("    color: orange;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("a:link, a:visited, a:active {\n");
      out.write("    color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write("article { \n");
      out.write("    position: relative;\n");
      out.write("    text-align: center;\n");
      out.write("    padding-top: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("p.menus{\n");
      out.write("	font-size: 20px;\n");
      out.write("	color:white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("hr {\n");
      out.write("    margin-top: -15px;\n");
      out.write("    width: 300px;\n");
      out.write("    background-color: rgb(209, 209, 209);\n");
      out.write("    border: none;\n");
      out.write("    height: 1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("footer {\n");
      out.write("    background-color: white;\n");
      out.write("    font-size: 12px;\n");
      out.write("    text-align: center;\n");
      out.write("    color: grey;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body{\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("html {\n");
      out.write("    scroll-behavior: smooth;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("#navimage{\n");
      out.write("	float: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#menu0 {\n");
      out.write("	margin: 50px;\n");
      out.write("	padding-bottom: 50px;\n");
      out.write("}\n");
      out.write("#menu1 {\n");
      out.write("	width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#menu2 {\n");
      out.write("	width: 100%;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"navbar\">\n");
      out.write("		<img src=\"../../img/musinsa_banner.png\" id=\"banner\">\n");
      out.write("		<ul id=\"nav\">\n");
      out.write("			<a href=\"../list\"><img src=\"../../img/musinsa_logo.png\" id=\"logo\"></a>\n");
      out.write("			<div class=\"search-container\">\n");
      out.write("				<input type=\"text\" class=\"search-box\" name=\"keyword\">\n");
      out.write("				<button class=\"search\" onClick=\"myFunction()\">\n");
      out.write("					<i class=\"fa fa-search\"></i>\n");
      out.write("				</button>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"dropdown-bar\">\n");
      out.write("				<li><a href=\"#menu0\"><p class=\"menus\">랭킹</p></a></li>\n");
      out.write("				<div class=\"dropdown\">\n");
      out.write("					<a href=\"#menu1\">상품</a><a href=\"#menu1\">브랜드</a><a href=\"#menu1\">검색어</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"dropdown-bar\">\n");
      out.write("				<li><a href=\"#menu1\"><p class=\"menus\">업데이트</p></a></li>\n");
      out.write("				<div class=\"dropdown\">\n");
      out.write("					<a href=\"#menu1\">신상품</a><a href=\"#menu1\">재입고</a><a href=\"#menu1\">세일소식</a>\n");
      out.write("					<a href=\"#menu1\">이벤트</a><a href=\"#menu1\">입점</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"dropdown-bar\">\n");
      out.write("				<li><a href=\"#menu2\"><p class=\"menus\">코디</p></a></li>\n");
      out.write("				<div class=\"dropdown\">\n");
      out.write("					<a href=\"#menu1\">코디숍</a><a href=\"#menu1\">코디맵</a><a href=\"#menu1\">브랜드 스냅</a>\n");
      out.write("					<a href=\"#menu1\">스트릿 스냅</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"dropdown-bar\">\n");
      out.write("				<li><a href=\"#menu3\"><p class=\"menus\">세일</p></a></li>\n");
      out.write("				<div class=\"dropdown\">\n");
      out.write("					<a href=\"#menu1\">쿠폰</a><a href=\"#menu1\">세일</a><a href=\"#menu1\">타임세일</a>\n");
      out.write("					<a href=\"#menu1\">기획전</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"dropdown-bar\">\n");
      out.write("				<li><a href=\"#menu4\"><p class=\"menus\">스페셜</p></a></li>\n");
      out.write("				<div class=\"dropdown\">\n");
      out.write("					<a href=\"#menu1\">쇼케이스</a><a href=\"#menu1\">스페셜 이슈</a><a href=\"#menu1\">단독상품</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"nav-right\">\n");
      out.write("			");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"small-container\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-2\">\n");
      out.write("					<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("					<img src='../../img/toffee.jpeg' width=\"80%\">\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-2\">\n");
      out.write("					<h1>Product Info</h1>\n");
      out.write("					<p>Brand: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getBrand()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("					<p>좋아요 수: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getRating()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("					<p>구매 후기: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getReview_num()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("					<br>\n");
      out.write("					<h1>Price Info</h1>\n");
      out.write("					<p>Price: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getPrice()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("					<br>\n");
      out.write("					<h1>Size Info</h1>\n");
      out.write("					<p>Size: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u.getSize()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("					<br>\n");
      out.write("					<h1>Add to cart</h1>\n");
      out.write("					<select>\n");
      out.write("						<option>사이즈</option>\n");
      out.write("						<option>M</option>\n");
      out.write("					</select> <input type=\"number\" value=\"1\"> <a href=\"\" class=\"btn\">장바구니\n");
      out.write("						넣기</a> <br> <br> <input type=\"button\" value=\"뒤로가기\"\n");
      out.write("						onclick=\"history.back()\" />\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<br />\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/detail.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/detail.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/detail.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
